### ISSUE TITLE
Way to group items from column

### ISSUE THREAD

**Issue by tjferry14** [chriszarate/sheetrock#106]
I did some fiddling around with the google query language to no avail, but is there any way to grab an entire column, and make a list of the items grouped together? (i.e., a column of fruits with multiple rows for pears, apples, oranges but the list would just return one list/row of: pears, apples, oranges)

Similar to the RBI leaders example, but since there's no numbers involved, I think grouping does not work for this.

**Comment by chriszarate** [comment]
Google's docs are a little squirrelly around grouping, and this note in particular makes it sound like you don't necessarily need an aggregation function if you want to group by a single column:

> If you use a group by clause, then every column listed in the select clause must either be listed in the group by clause, or be wrapped by an aggregation function.

That's inaccurate. You _need_ an aggregation function (e.g., `count` or `sum`) in order to make grouping work. But, if you're using templates, you don't have to _use_ the aggregated value.

For instance: 

```js
// Define spreadsheet URL.
var mySpreadsheet = 'https://docs.google.com/spreadsheets/d/1qT1LyvoAcb0HTsi2rHBltBVpUBumAUzT__rhMvrz5Rk/edit#gid=0';

// Get a list of all teams in alpha order.
$('#switch-hitters').sheetrock({
  url: mySpreadsheet,
  query: "select A,count(B) group by A order by A"
});
```

This returns a two-column list: teams and the number of players in each. (The value of `B` is irrelevant—it's just counting the rows.)

**Comment by tjferry14** [comment]
Thank you for your help! Very much appreciated!
