### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by tjferry14** [chriszarate/sheetrock#66]
How should links be handled in cells?

**Comment by chriszarate** [comment]
I've not done a ton of testing in this area, so the current behavior could probably be improved. Do you have an example Sheet or Fiddle you could share?

**Comment by tjferry14** [comment]
https://jsfiddle.net/m04ddeu2/486/ Here's an fiddle with the sheet I'm trying to use. Also need to fix the header rows.

**Comment by chriszarate** [comment]
I'm not able to access the Sheet directly for some reason. It looks like links are supposed to be in column E? I'm not sure what it looks like in the Sheet but no data is coming through. Perhaps try removing the links by right-clicking and selecting "Unlink" (so that the values are text)?

For the header rows, try removing the `headers` options and identifying the header row in the Sheet with View > Freeze rows > 1 row.

**Comment by tjferry14** [comment]
I had to tweak the link to make it usable. Here's the original link https://docs.google.com/spreadsheets/d/1ERW9nHeg7N91eZC4BNCJjA8jsh5yRjxkahuMAE38DPY/edit?usp=sharing

**Comment by chriszarate** [comment]
Closing as discussion shifted to another ticket.
