### ISSUE TITLE
Fail to request when strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by raingo** [chriszarate/sheetrock#71]
Please go to http://victorychinese.com/sermons/2015/index.html using "Incognito" mode of recent Chrome, and open the console.
The Chrome version is Version 43.0.2357.81 (64-bit)
The strange thing is the page works perfectly with regular browser, but request errors happen with only "incognito" mode.
Please have a look at this issue.

Thanks,
Raingo

**Comment by raingo** [comment]
Just confirmed. Everything works in the normal mode just because there are cookies. When I delete the cookies, the request errors happen in the normal mode as well.

**Comment by chriszarate** [comment]
The issue is that the Sheet you are querying is not public. I receive an error both in regular and incognito browser windows. It works for you in a regular browser window because you are signed in to Google in that browser session, and you have access to that private Sheet.

Make your Sheet public and it will work.

https://support.google.com/drive/bin/answer.py?hl=en&answer=2494822

**Comment by raingo** [comment]
Thanks. I just figured it out. Publishing it is not enough. I need to make it at least viewable to everyone.

Not sure if this would be a confusion for others. 

Definitely thanks for this great plugin!
