### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by adesignl** [chriszarate/sheetrock#97]
I get the error **SyntaxError: Unexpected token '<'** when I use Sheetrock in Safari Mobile. It looks  like it has to do with the ajax headers but i change them to text/html it sheetrock no longer works.

**Comment by chriszarate** [comment]
That looks like it's returning HTML (probably an error page) instead of JSON. That can happen if the permissions on the sheet are incorrect, or if there is something wrong with your Google credentials in that browser session. It's almost certainly not related to using mobile Safari.

If you've tried the basic stuff, try to replicate in an incognito window, or remote debug using a USB cable.
